"""empty message

Revision ID: a6e5fd48c51b
Revises: 9d98d897e1ce
Create Date: 2021-05-08 23:38:34.014737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e5fd48c51b'
down_revision = '9d98d897e1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_date')
    op.drop_column('Artist', 'created_date')
    # ### end Alembic commands ###
